const http = require("http");
const { URL } = require("url");
const channels = require("./kick_channels.json");

const PORT = Number(process.env.PORT || 10000);
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/140 Safari/537.36";
const VERSION = "2026-09-16-kick-render-v2-playback";

function norm(s) { return String(s || "").toLowerCase().replace(/[^a-z0-9\u3040-\u30ff\u3400-\u9fff]+/g, ""); }
function flattenObjects(value, out = []) { if (!value || typeof value !== "object") return out; if (Array.isArray(value)) { for (const v of value) flattenObjects(v,out); return out; } out.push(value); for (const v of Object.values(value)) flattenObjects(v,out); return out; }
async function getJson(url) { for (let attempt=0; attempt<3; attempt++) { try { const r=await fetch(url,{headers:{accept:"application/json, text/plain, */*","user-agent":UA,referer:"https://kick.com/","cache-control":"no-cache",pragma:"no-cache"},cache:"no-store"}); if(r.ok){try{return await r.json();}catch{}} } catch{} if(attempt<2) await new Promise(r=>setTimeout(r,250*(attempt+1))); } return null; }
function playbackOf(o){return o?.data||o?.playback_url||o?.playbackUrl||o?.stream?.playback_url||o?.stream?.playbackUrl||o?.livestream?.playback_url||o?.livestream?.playbackUrl||null;}
async function hlsAlive(url){if(!url)return false;try{const r=await fetch(url,{headers:{accept:"application/vnd.apple.mpegurl, application/x-mpegURL, text/plain, */*","user-agent":UA,referer:"https://kick.com/"},cache:"no-store",redirect:"follow"});if(!r.ok)return false;const t=await r.text();return t.includes("#EXTM3U");}catch{return false;}}
async function resolveSlug(slug){if(!slug)return null; const fresh=await getJson("https://kick.com/api/v2/channels/"+encodeURIComponent(slug)+"/playback-url"); const freshPlayback=playbackOf(fresh); if(freshPlayback&&await hlsAlive(freshPlayback))return {slug,playback:freshPlayback,source:"playback-url"}; const data=await getJson("https://kick.com/api/v2/channels/"+encodeURIComponent(slug)); if(!data||!data.livestream)return null; const playback=playbackOf(data); if(!playback||!await hlsAlive(playback))return null; return {slug:data.slug||slug,playback,source:"channel"};}
async function searchCandidates(item){const terms=[item.search,...(Array.isArray(item.match_terms)?item.match_terms:[]),item.name].filter(Boolean); const wanted=new Set(terms.map(norm).filter(Boolean)); const found=[]; for(const term of terms.slice(0,5)){const data=await getJson("https://kick.com/api/search?query="+encodeURIComponent(term)); if(!data)continue; for(const obj of flattenObjects(data)){const slug=obj.slug||obj.channel_slug||obj.username||obj.name; if(!slug||typeof slug!=="string")continue; const hay=norm([obj.slug,obj.username,obj.name,obj.session_title,obj.title].filter(Boolean).join(" ")); if(wanted.size&&![...wanted].some(x=>x&&hay.includes(x)))continue; found.push(slug);}} return [...new Set(found)];}
async function resolveLive(item){const slugs=[item.slug,...(Array.isArray(item.slug_aliases)?item.slug_aliases:[])].filter(Boolean); for(const slug of [...new Set(slugs)]){const hit=await resolveSlug(slug); if(hit)return hit;} const searched=await searchCandidates(item); for(const slug of searched){const hit=await resolveSlug(slug); if(hit)return hit;} return null;}
function findM3u8(value){if(!value)return null; if(typeof value==="string")return /^https?:\/\//i.test(value)&&value.includes(".m3u8")?value:null; if(Array.isArray(value)){for(const x of value){const h=findM3u8(x);if(h)return h;}return null;} if(typeof value==="object"){for(const k of ["source","playback_url","playbackUrl","hls_url","hlsUrl","stream_url","streamUrl"]){const h=findM3u8(value[k]);if(h)return h;}for(const x of Object.values(value)){const h=findM3u8(x);if(h)return h;}} return null;}
async function getText(url){const r=await fetch(url,{headers:{accept:"application/vnd.apple.mpegurl, application/x-mpegURL, text/plain, */*","user-agent":UA,referer:"https://kick.com/"},cache:"no-store"});if(!r.ok)throw new Error(`HLS fetch failed ${r.status}`);return await r.text();}
function absolute(base,value){try{return new URL(value,base).toString();}catch{return value;}}
function rewritePlaylist(text,source,startSeconds){const out=[];const lines=String(text||"").replace(/\r/g,"").split("\n");let inserted=false;for(let line of lines){if(!inserted&&line.startsWith("#EXTM3U")){out.push(line);out.push(`#EXT-X-START:TIME-OFFSET=${startSeconds},PRECISE=YES`);inserted=true;continue;}if(line.startsWith("#")){line=line.replace(/URI="([^"]+)"/g,(_,uri)=>`URI="${absolute(source,uri)}"`);out.push(line);continue;}out.push(line.trim()?absolute(source,line.trim()):line);}if(!inserted)out.unshift(`#EXT-X-START:TIME-OFFSET=${startSeconds},PRECISE=YES`);return out.join("\n");}
function headers(res){res.setHeader("Cache-Control","no-store, max-age=0");res.setHeader("Pragma","no-cache");res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("X-Kick-Resolver-Version",VERSION);}
function json(res,status,obj){headers(res);res.statusCode=status;res.setHeader("Content-Type","application/json; charset=utf-8");res.end(JSON.stringify(obj));}
function redirect(res,url){headers(res);res.statusCode=302;res.setHeader("Location",url);res.end();}
async function handleVod(q,res){const vod=String(q.get("vod")||"").trim();if(!/^[A-Za-z0-9_-]{6,120}$/.test(vod))return json(res,400,{error:"invalid KICK VOD id",resolver:VERSION});let start=Number(q.get("start")||0);if(!Number.isFinite(start)||start<0)start=0;start=Math.floor(Math.min(start,7*24*60*60));const data=await getJson("https://kick.com/api/v1/video/"+encodeURIComponent(vod));if(!data)return json(res,404,{error:"KICK VOD metadata unavailable",vod,resolver:VERSION});const source=findM3u8(data);if(!source)return json(res,410,{error:"KICK VOD media unavailable",vod,resolver:VERSION});res.setHeader("X-Kick-VOD-Id",vod);res.setHeader("X-Kick-Replay-Start",String(start));if(!start)return redirect(res,source);try{const playlist=await getText(source);const rewritten=rewritePlaylist(playlist,source,start);headers(res);res.statusCode=200;res.setHeader("Content-Type","application/vnd.apple.mpegurl; charset=utf-8");res.end(rewritten);}catch(e){return json(res,502,{error:"KICK VOD seek playlist failed",vod,start,detail:String(e?.message||e),resolver:VERSION});}}
async function handler(req,res){const u=new URL(req.url,"http://localhost");if(u.pathname==="/health")return json(res,200,{ok:true,resolver:VERSION});if(u.pathname!=="/kick"&&u.pathname!=="/api/kick"&&u.pathname!=="/api/kick-replay")return json(res,404,{error:"not found",resolver:VERSION});if(u.searchParams.get("vod"))return handleVod(u.searchParams,res);const key=String(u.searchParams.get("ch")||"").toLowerCase();const aliases={gccx:"kick.gccx",gccx2:"kick.gccx2",nogizaka:"kick.nogizaka",nogi:"kick.nogizaka"};const tvgId=aliases[key]||key;const item=channels.find(x=>String(x.tvg_id||"").toLowerCase()===tvgId);if(!item)return json(res,404,{error:"unknown KICK channel",resolver:VERSION});try{const hit=await resolveLive(item);if(!hit)return json(res,503,{error:"KICK live playback unavailable",tvg_id:item.tvg_id,slug:item.slug,resolver:VERSION});res.setHeader("X-Kick-Resolved-Slug",hit.slug);res.setHeader("X-Kick-Playback-Source",hit.source||"");return redirect(res,hit.playback);}catch(e){return json(res,502,{error:"KICK resolver failed",detail:String(e?.message||e),resolver:VERSION});}}

http.createServer((req,res)=>{handler(req,res).catch(e=>json(res,500,{error:"internal error",detail:String(e?.message||e),resolver:VERSION}));}).listen(PORT,"0.0.0.0",()=>console.log(`KICK resolver ${VERSION} listening on ${PORT}`));
