const http = require("http");
const { URL } = require("url");
const channels = require("./kick_channels.json");
const PORT = Number(process.env.PORT || 10000);
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/140 Safari/537.36";
const VERSION = "2026-09-22-render-v10-kick-aliases";

async function getJson(url){for(let a=0;a<3;a++){try{const r=await fetch(url,{headers:{accept:"application/json, text/plain, */*","user-agent":UA,referer:"https://kick.com/","cache-control":"no-cache"},cache:"no-store"});if(r.ok){try{return await r.json()}catch{}}}catch{}if(a<2)await new Promise(r=>setTimeout(r,300*(a+1)))}return null}
async function getJsonHeaders(url,extra={}){for(let a=0;a<3;a++){try{const r=await fetch(url,{headers:{accept:"application/json, text/plain, */*","user-agent":UA,"cache-control":"no-cache",...extra},cache:"no-store"});if(r.ok){try{return await r.json()}catch{}}}catch{}if(a<2)await new Promise(r=>setTimeout(r,300*(a+1)))}return null}
async function getText(url,referer="https://kick.com/"){const r=await fetch(url,{headers:{accept:"application/vnd.apple.mpegurl, application/x-mpegURL, text/plain, */*","user-agent":UA,referer,"cache-control":"no-cache",pragma:"no-cache"},cache:"no-store"});if(!r.ok)throw new Error(`HLS fetch failed ${r.status}`);return await r.text()}
async function fetchJson(url,opts={}){for(let a=0;a<3;a++){try{const r=await fetch(url,{...opts,headers:{accept:"application/json, text/plain, */*","user-agent":UA,...(opts.headers||{})},cache:"no-store"});if(r.ok){try{return await r.json()}catch{}}}catch{}if(a<2)await new Promise(r=>setTimeout(r,300*(a+1)))}return null}
function abs(base,v){try{return new URL(v,base).toString()}catch{return v}}
function findM3u8(v){if(!v)return null;if(typeof v==="string")return /^https?:\/\//i.test(v)&&v.includes(".m3u8")?v:null;if(Array.isArray(v)){for(const x of v){const h=findM3u8(x);if(h)return h}}else if(typeof v==="object"){for(const k of ["source","playback_url","playbackUrl","hls_url","hlsUrl","stream_url","streamUrl"]){const h=findM3u8(v[k]);if(h)return h}for(const x of Object.values(v)){const h=findM3u8(x);if(h)return h}}return null}
async function alive(url){if(!url)return false;try{return (await getText(url)).includes("#EXTM3U")}catch{return false}}
async function resolveSlug(slug){for(const ep of [`https://kick.com/api/v2/channels/${encodeURIComponent(slug)}/livestream`,`https://kick.com/api/v1/channels/${encodeURIComponent(slug)}/livestream`,`https://kick.com/api/v2/channels/${encodeURIComponent(slug)}/playback-url`,`https://kick.com/api/v2/channels/${encodeURIComponent(slug)}`]){const data=await getJson(ep),url=findM3u8(data);if(url&&await alive(url))return {slug,playback:url}}return null}
async function resolveLive(item){for(const slug of [...new Set([item.slug,...(item.slug_aliases||[])].filter(Boolean))]){const h=await resolveSlug(slug);if(h)return h}return null}
function headers(res){res.setHeader("Cache-Control","no-store, max-age=0");res.setHeader("Pragma","no-cache");res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("X-Media-Resolver-Version",VERSION)}
function json(res,status,obj){headers(res);res.statusCode=status;res.setHeader("Content-Type","application/json; charset=utf-8");res.end(JSON.stringify(obj))}
function redirect(res,url){headers(res);res.statusCode=302;res.setHeader("Location",url);res.end()}
function m3u(res,text){headers(res);res.statusCode=200;res.setHeader("Content-Type","application/vnd.apple.mpegurl; charset=utf-8");res.end(text)}


function rewriteM3u(text,source){return String(text||"").replace(/\r/g,"").split("\n").map(line=>{if(line.startsWith("#"))return line.replace(/URI="([^"]+)"/g,(_,x)=>`URI="${abs(source,x)}"`);return line.trim()?abs(source,line.trim()):line}).join("\n")}
function findPlayableM3u8(v){if(!v)return null;if(Array.isArray(v)){for(const x of v){const h=findPlayableM3u8(x);if(h)return h}return null}if(typeof v==="object"){const typ=String(v.type||"").toLowerCase();if(!v.key_systems&&typeof v.src==="string"&&/^https?:\/\//i.test(v.src)&&(v.src.includes(".m3u8")||typ.includes("mpegurl")||typ.includes("m3u8")))return v.src;for(const x of Object.values(v)){const h=findPlayableM3u8(x);if(h)return h}}return null}
function tverKeyName(){const d=new Date(Date.now()+9*3600000),m=d.getUTCMonth()+1,n=m%6||6;return `key0${n}`}
async function resolveTver(ep){
  const meta=await fetchJson(`https://statics.tver.jp/content/episode/${encodeURIComponent(ep)}.json?v=5`,{headers:{referer:"https://tver.jp/"}});
  if(!meta)throw new Error("TVer episode metadata unavailable");
  const project=meta?.streaks?.projectID,ref=meta?.streaks?.videoRefID;
  if(project&&ref){
    try{
      const keys=await fetchJson("https://player.tver.jp/player/streaks_info_v2.json",{headers:{referer:"https://tver.jp/"}});
      const apiKey=keys?.[project]?.api_key?.[tverKeyName()];
      if(apiKey){
        const mediaId=String(ref).startsWith("ref:")?String(ref):`ref:${ref}`;
        const play=await fetchJson(`https://playback.api.streaks.jp/v1/projects/${encodeURIComponent(project)}/medias/${encodeURIComponent(mediaId)}`,{headers:{origin:"https://tver.jp",referer:"https://tver.jp/","x-streaks-api-key":apiKey}});
        const source=findPlayableM3u8(play?.sources);
        if(source)return {source,project,mediaId,title:meta?.title||ep,backend:"streaks"};
        if(findM3u8(play?.sources))throw new Error("TVer stream is DRM-protected");
      }
    }catch{}
  }
  const account=String(meta?.video?.accountID||"").trim(),player=String(meta?.video?.playerID||"").trim(),videoRef=String(meta?.video?.videoRefID||"").trim();
  if(account&&player&&videoRef){
    const cfg=await fetchJson(`https://players.brightcove.net/${encodeURIComponent(account)}/${encodeURIComponent(player)}_default/config.json`,{headers:{referer:"https://tver.jp/"}});
    const policy=cfg?.video_cloud?.policy_key;
    if(policy){
      const bcId=videoRef.startsWith("ref:")?videoRef:`ref:${videoRef}`;
      const bc=await fetchJson(`https://edge.api.brightcove.com/playback/v1/accounts/${encodeURIComponent(account)}/videos/${encodeURIComponent(bcId)}`,{headers:{"bcov-policy":policy,origin:"https://tver.jp",referer:"https://tver.jp/"}});
      const source=findPlayableM3u8(bc?.sources);
      if(source)return {source,project:"brightcove-"+account,mediaId:bcId,title:meta?.title||ep,backend:"brightcove"};
    }
  }
  throw new Error("TVer HLS source unavailable");
}
async function tverVod(u,res){const ep=String(u.searchParams.get("ep")||"").trim();if(!/^[A-Za-z0-9]{6,40}$/.test(ep))return json(res,400,{error:"invalid TVer episode id",resolver:VERSION});try{const hit=await resolveTver(ep);let media=hit.source,text=await getText(media,"https://tver.jp/");for(let d=0;d<3&&/#EXT-X-STREAM-INF:/i.test(text);d++){const v=pickVariant(text,media);if(!v)throw new Error("TVer master playlist has no variant");media=v;text=await getText(media,"https://tver.jp/")}if(/#EXT-X-STREAM-INF:/i.test(text))throw new Error("TVer nested master playlist too deep");res.setHeader("X-TVer-Project",hit.project);res.setHeader("X-TVer-Media",hit.mediaId);res.setHeader("X-TVer-Backend",hit.backend||"unknown");return m3u(res,rewriteM3u(text,media))}catch(e){return json(res,502,{error:"TVer playback unavailable",ep,detail:String(e?.message||e),resolver:VERSION})}}

function rewriteKick(text,source,start){const out=[];let inserted=false;for(let line of String(text||"").replace(/\r/g,"").split("\n")){if(!inserted&&line.startsWith("#EXTM3U")){out.push(line,`#EXT-X-START:TIME-OFFSET=${start},PRECISE=YES`);inserted=true;continue}if(line.startsWith("#")){out.push(line.replace(/URI="([^"]+)"/g,(_,x)=>`URI="${abs(source,x)}"`));continue}out.push(line.trim()?abs(source,line.trim()):line)}if(!inserted)out.unshift(`#EXT-X-START:TIME-OFFSET=${start},PRECISE=YES`);return out.join("\n")}
async function kickVod(u,res){const vod=String(u.searchParams.get("vod")||"").trim();if(!/^[A-Za-z0-9_-]{6,120}$/.test(vod))return json(res,400,{error:"invalid KICK VOD id",resolver:VERSION});let start=Number(u.searchParams.get("start")||0);if(!Number.isFinite(start)||start<0)start=0;start=Math.floor(Math.min(start,604800));let duration=Number(u.searchParams.get("duration")||0);if(!Number.isFinite(duration)||duration<0)duration=0;duration=duration?Math.max(30,Math.min(Math.floor(duration),43200)):0;const data=await getJson("https://kick.com/api/v1/video/"+encodeURIComponent(vod));if(!data)return json(res,404,{error:"KICK VOD metadata unavailable",vod,resolver:VERSION});const source=findM3u8(data);if(!source)return json(res,410,{error:"KICK VOD media unavailable",vod,resolver:VERSION});if(!start&&!duration)return redirect(res,source);try{let media=source,text=await getText(media);for(let d=0;d<3&&/#EXT-X-STREAM-INF:/i.test(text);d++){const v=pickVariant(text,media);if(!v)throw new Error("master playlist has no variant");media=v;text=await getText(media)}if(/#EXT-X-STREAM-INF:/i.test(text))throw new Error("nested master playlist too deep");if(duration){const clipped=rewriteHaru(text,media,start,duration).replace("# HARU clip requested","# KICK clip requested");return m3u(res,clipped)}return m3u(res,rewriteKick(text,media,start))}catch(e){return json(res,502,{error:"KICK VOD clip playlist failed",vod,start,duration,detail:String(e?.message||e),resolver:VERSION})}}

function allowedHaru(raw){try{const x=new URL(raw);return x.protocol==="https:"&&x.hostname==="haru.charandom.blog"&&/\/stream\/jp\/[^/]+\/replay\.m3u8$/i.test(x.pathname)}catch{return false}}
function pickVariant(text,source){const ls=String(text||"").replace(/\r/g,"").split("\n"),c=[];for(let i=0;i<ls.length;i++){if(!ls[i].trim().startsWith("#EXT-X-STREAM-INF:"))continue;const bw=Number((ls[i].match(/BANDWIDTH=(\d+)/i)||[])[1]||0);for(let j=i+1;j<ls.length;j++){const n=ls[j].trim();if(!n)continue;if(n.startsWith("#"))break;c.push({bw,url:abs(source,n)});break}}c.sort((a,b)=>b.bw-a.bw);return c[0]?.url||null}
function rewriteHaru(text,source,offset,duration){const ls=String(text||"").replace(/\r/g,"").split("\n"),header=[],groups=[];let tags=[],inf=null;const hdr=l=>l==="#EXTM3U"||/^#EXT-X-(VERSION|TARGETDURATION|MEDIA-SEQUENCE|DISCONTINUITY-SEQUENCE|PLAYLIST-TYPE|INDEPENDENT-SEGMENTS|ALLOW-CACHE)/.test(l);for(const raw of ls){let l=raw.trim();if(!l||l==="#EXT-X-ENDLIST")continue;if(l.startsWith("#EXTINF:")){inf={line:l,seconds:Number((l.match(/^#EXTINF:([0-9.]+)/)||[])[1]||0)};continue}if(l.startsWith("#")){l=l.replace(/URI="([^"]+)"/g,(_,x)=>`URI="${abs(source,x)}"`);if(!inf&&!groups.length&&!tags.length&&hdr(l))header.push(l);else tags.push(l);continue}if(inf){groups.push({tags,inf:inf.line,seconds:Math.max(0,inf.seconds||0),uri:abs(source,l)});tags=[];inf=null}}if(!groups.length)throw new Error("no media segments found");let cum=0,total=0,skipped=0,key=null,map=null;const sel=[];for(const g of groups){for(const t of g.tags){if(t.startsWith("#EXT-X-KEY:"))key=t;if(t.startsWith("#EXT-X-MAP:"))map=t}const s=cum,e=cum+g.seconds;cum=e;if(e<=offset+.001){skipped++;continue}if(s>=offset+duration-.001)break;const t=[...g.tags];if(!sel.length){if(key&&!t.some(x=>x.startsWith("#EXT-X-KEY:")))t.unshift(key);if(map&&!t.some(x=>x.startsWith("#EXT-X-MAP:")))t.unshift(map);t.unshift("#EXT-X-START:TIME-OFFSET=0,PRECISE=YES",`# HARU clip requested offset=${offset}s actual_segment_start=${s.toFixed(3)}s`)}sel.push({...g,tags:t});total+=g.seconds}if(!sel.length)throw new Error(`offset ${offset}s is outside available replay`);const out=header.map(l=>{const z=l.match(/^#EXT-X-MEDIA-SEQUENCE:(\d+)/);return z?`#EXT-X-MEDIA-SEQUENCE:${Number(z[1])+skipped}`:l});if(!out.includes("#EXTM3U"))out.unshift("#EXTM3U");for(const g of sel)out.push(...g.tags,g.inf,g.uri);out.push("#EXT-X-ENDLIST");return out.join("\n")+"\n"}
async function haruClip(u,res){const src=String(u.searchParams.get("src")||"").trim();let offset=Number(u.searchParams.get("offset")||0),duration=Number(u.searchParams.get("duration")||600);if(!Number.isFinite(offset))offset=0;if(!Number.isFinite(duration))duration=600;offset=Math.max(0,Math.min(Math.floor(offset),28800));duration=Math.max(30,Math.min(Math.floor(duration),3600));if(!allowedHaru(src))return json(res,400,{error:"invalid HARU replay source",resolver:VERSION});try{let media=src,text=await getText(media,"https://haru.charandom.blog/");for(let d=0;d<2&&/#EXT-X-STREAM-INF:/i.test(text);d++){const v=pickVariant(text,media);if(!v)throw new Error("master playlist has no variant");media=v;text=await getText(media,"https://haru.charandom.blog/")}if(/#EXT-X-STREAM-INF:/i.test(text))throw new Error("nested master playlist too deep");return m3u(res,rewriteHaru(text,media,offset,duration))}catch(e){return json(res,502,{error:"HARU clip playlist failed",offset,duration,detail:String(e?.message||e),resolver:VERSION})}}

async function handler(req,res){const u=new URL(req.url,"http://localhost");if(u.pathname==="/health")return json(res,200,{ok:true,resolver:VERSION,features:["kick-live","kick-vod","kick-vod-clip","haru-clip","tver-vod"]});if(u.pathname==="/tver"||u.pathname==="/api/tver")return tverVod(u,res);if(u.pathname==="/haru-clip"||u.pathname==="/api/haru-clip")return haruClip(u,res);if(u.pathname!=="/kick"&&u.pathname!=="/api/kick"&&u.pathname!=="/api/kick-replay")return json(res,404,{error:"not found",resolver:VERSION});if(u.searchParams.has("vod"))return kickVod(u,res);const aliases={gccx:"kick.gccx",gccx2:"kick.gccx2",nogizaka:"kick.nogizaka",nogi:"kick.nogizaka",seiz:"kick.seiz",kujotaizai:"kick.kujotaizai",kujo:"kick.kujotaizai",wekiukk7:"kick.kujotaizai"};const key=String(u.searchParams.get("ch")||"").toLowerCase(),id=aliases[key]||key,item=channels.find(x=>String(x.tvg_id||"").toLowerCase()===id);if(!item)return json(res,404,{error:"unknown KICK channel",resolver:VERSION});const hit=await resolveLive(item);if(!hit)return json(res,503,{error:"KICK live playback unavailable",tvg_id:item.tvg_id,slug:item.slug,resolver:VERSION});return redirect(res,hit.playback)}
http.createServer((req,res)=>handler(req,res).catch(e=>json(res,500,{error:"internal error",detail:String(e?.message||e),resolver:VERSION}))).listen(PORT,"0.0.0.0",()=>console.log(`Media resolver ${VERSION} listening on ${PORT}`));
