#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import re
import urllib.parse
from pathlib import Path
from urllib.parse import quote

FREEWIFI = Path("freewifi")
RADIO_PROJECTION = Path("radio/freewifi.m3u")
RADIO_AUDIO_BASE = "https://himitsu-six.vercel.app/api/radiko"
RADIO_VERCEL_BASE = "https://himitsu-six.vercel.app/api/radio-tv?station="
RADIO_RAILWAY_BASE = "https://freewifi-radio-production.up.railway.app/radio-tv"
RADIO_BUILD = "20260929d"
# All Radiko stations in FreeWiFi now use Railway's on-demand MPEG-TS card.
# The old Vercel route used radio-ts-assets cards that were generated without
# Japanese fonts and displayed kanji/kana as tofu squares.
VERCEL_RADIKO_SIDS = set()
RAILWAY_RADIKO_SIDS = {
    "JOEU-FM", "RNB", "LFR", "QRR", "TBS", "FMT",
    "ABC", "CCL", "802", "FMO", "MBS", "OBC", "KBS",
    "ALPHA-STATION", "E-RADIO", "CRK",
    "HBC", "TBC", "CBC", "RCC", "RKB", "KBC",
}
VERCEL_NHK_SIDS = {"nhk_r1_matsuyama"}
ALL_RADIKO_SIDS = VERCEL_RADIKO_SIDS | RAILWAY_RADIKO_SIDS
LOGO_RAW_BASE = "https://raw.githubusercontent.com/ajiousama/himitsu/main"
EXPECTED_RADIO_COUNT = 28
EXPECTED_RADIKO_COUNT = 22
EXPECTED_VERCEL_ROUTE_COUNT = 1


def radio_url(sid: str) -> str:
    if sid in VERCEL_RADIKO_SIDS or sid in VERCEL_NHK_SIDS:
        return f"{RADIO_VERCEL_BASE}{quote(sid, safe='')}"
    return f"{RADIO_RAILWAY_BASE}/{quote(sid, safe='')}?v={RADIO_BUILD}"


def source_logo_url(sid: str) -> str:
    return f"https://radiko.jp/v2/static/station/logo/{sid}/lrtrim/688x160.png"


def safe_slug(value: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip())
    return value.strip("._-") or "logo"


def contrast_logo_from_source(tvgid: str, source: str) -> str:
    digest = hashlib.sha1(source.encode("utf-8")).hexdigest()[:8]
    relpath = f"logos/contrast/{safe_slug(tvgid)}_{digest}.png"
    return f"{LOGO_RAW_BASE}/{urllib.parse.quote(relpath, safe='/._-')}"


def contrast_logo_url(tvgid: str, sid: str) -> str:
    return contrast_logo_from_source(tvgid, source_logo_url(sid))


def radio_entry(tvgid: str, station: str, name: str, logo: str) -> str:
    return (
        f'#EXTINF:-1 tvg-id="{tvgid}" tvg-logo="{logo}" group-title="ラジオ",{name}\n'
        f'{radio_url(station)}\n'
    )


def radiko_entry(tvgid: str, sid: str, name: str, logo: str | None = None) -> str:
    if logo is None:
        # Use the local white-card asset generated by logo_contrast_apply.py.
        # This keeps black-background IPTV clients from swallowing dark or
        # transparent station artwork.
        logo = contrast_logo_url(tvgid, sid)
    return radio_entry(tvgid, sid, name, logo)


def compact_block() -> str:
    parts: list[str] = ["## ラジオ\n\n"]

    stations = [
        ("radiko.JOEU-FM", "JOEU-FM", "FM愛媛（ラジオ）"),
        ("radiko.RNB", "RNB", "RNB南海放送（ラジオ）"),
        ("radiko.LFR", "LFR", "ニッポン放送（ラジオ）"),
        ("radiko.QRR", "QRR", "文化放送（ラジオ）"),
        ("radiko.TBS", "TBS", "TBSラジオ（ラジオ）"),
        ("radiko.FMT", "FMT", "TOKYO FM（ラジオ）"),
        ("radiko.ABC", "ABC", "ABCラジオ（ラジオ）"),
        ("radiko.CCL", "CCL", "FM COCOLO（ラジオ）"),
        ("radiko.802", "802", "FM802（ラジオ）"),
        ("radiko.FMO", "FMO", "FM大阪（ラジオ）"),
        ("radiko.MBS", "MBS", "MBSラジオ（ラジオ）"),
        ("radiko.OBC", "OBC", "OBCラジオ大阪（ラジオ）"),
        ("radiko.KBS", "KBS", "KBS京都ラジオ（ラジオ）"),
        ("radiko.ALPHA-STATION", "ALPHA-STATION", "α-STATION FM KYOTO（ラジオ）"),
        ("radiko.E-RADIO", "E-RADIO", "e-radio FM滋賀（ラジオ）"),
        ("radiko.CRK", "CRK", "ラジオ関西（ラジオ）"),
        ("radiko.HBC", "HBC", "HBCラジオ（ラジオ）"),
        ("radiko.TBC", "TBC", "tbcラジオ（ラジオ）"),
        ("radiko.CBC", "CBC", "CBCラジオ（ラジオ）"),
        ("radiko.RCC", "RCC", "RCCラジオ（ラジオ）"),
        ("radiko.RKB", "RKB", "RKBラジオ（ラジオ）"),
        ("radiko.KBC", "KBC", "KBCラジオ（ラジオ）"),
    ]
    parts.extend(radiko_entry(tvgid, sid, name) for tvgid, sid, name in stations)

    parts.append(
        radio_entry(
            "nhk_r1_matsuyama",
            "nhk_r1_matsuyama",
            "NHKラジオ第1（松山）",
            "https://raw.githubusercontent.com/ajiousama/himitsu/main/logos/contrast/nhk_r1_matsuyama_667dbb12.png",
        )
    )

    # Community FM: same Railway image+audio route and same ラジオ group as the
    # existing stations, but their public simulcast audio does not use Radiko.
    parts.append(
        radio_entry(
            "community.FMOTOKUNI",
            "FMOTOKUNI",
            "FMおとくに（ラジオ）",
            contrast_logo_from_source("community.FMOTOKUNI", "https://www.simulradio.info/data/161.jpg"),
        )
    )
    parts.append(
        radio_entry(
            "community.FM845",
            "FM845",
            "FM845（ラジオ）",
            "https://raw.githubusercontent.com/ajiousama/himitsu/main/logos/contrast/community.FM845_ce4a3561.png",
        )
    )
    parts.append(
        radio_entry(
            "community.BARIBARI",
            "BARIBARI",
            "FMラヂオバリバリ（ラジオ）",
            "https://raw.githubusercontent.com/ajiousama/himitsu/main/logos/contrast/community.BARIBARI_c65da997.png",
        )
    )
    parts.append(
        radio_entry(
            "community.NIIHAMA",
            "NIIHAMA",
            "Hello! NEW 新居浜 FM78.0（ラジオ）",
            "https://raw.githubusercontent.com/ajiousama/himitsu/main/logos/contrast/community.NIIHAMA_d9a30115.png",
        )
    )
    parts.append(
        radio_entry(
            "community.FMGAIYA",
            "FMGAIYA",
            "FMがいや 76.9MHz（ラジオ）",
            "https://raw.githubusercontent.com/ajiousama/himitsu/main/logos/contrast/community.FMGAIYA_fb1724db.png",
        )
    )

    return "".join(parts).rstrip() + "\n\n"


def main() -> int:
    text = FREEWIFI.read_text(encoding="utf-8-sig", errors="replace")
    start = text.find("## ラジオ")
    end = text.find("## 愛媛CATV", start + 1)
    if start < 0 or end < 0 or end <= start:
        raise RuntimeError("could not locate radio section boundaries")

    block = compact_block()
    RADIO_PROJECTION.parent.mkdir(parents=True, exist_ok=True)
    RADIO_PROJECTION.write_text("#EXTM3U\n\n" + block, encoding="utf-8")
    updated = text[:start] + block + text[end:]

    if "## Rch" not in updated:
        raise RuntimeError("Rch section disappeared; refusing to write")

    radio_section = updated[start:updated.find("## 愛媛CATV", start)]
    vercel_count = radio_section.count(RADIO_VERCEL_BASE)
    render_count = radio_section.count(RADIO_RAILWAY_BASE + "/")
    if vercel_count != EXPECTED_VERCEL_ROUTE_COUNT or render_count != EXPECTED_RADIO_COUNT - EXPECTED_VERCEL_ROUTE_COUNT:
        raise RuntimeError(
            f"compact FreeWiFi radio routing unexpected: vercel={vercel_count} railway={render_count}"
        )
    if RADIO_AUDIO_BASE + "?station=" in radio_section:
        raise RuntimeError("audio-only route leaked into FreeWiFi radio section")
    extinf_lines = [line for line in radio_section.splitlines() if line.startswith("#EXTINF:")]
    if len(extinf_lines) != EXPECTED_RADIO_COUNT or any('group-title="ラジオ"' not in line for line in extinf_lines):
        raise RuntimeError("FreeWiFi radio groups are not uniformly ラジオ")
    if "### 北海道" in radio_section:
        raise RuntimeError("nationwide catalog leaked into FreeWiFi radio section")
    if "raw.githubusercontent.com/ajiousama/himitsu/radio-ts-assets/" in radio_section:
        raise RuntimeError("TS visual master leaked into compact FreeWiFi radio section")
    if radio_section.count("/logos/contrast/radiko.") != EXPECTED_RADIKO_COUNT:
        raise RuntimeError("contrast-safe compact Radiko logos are not complete")

    if f'{RADIO_VERCEL_BASE}nhk_r1_matsuyama' not in radio_section:
        raise RuntimeError("required Vercel NHK station missing: nhk_r1_matsuyama")
    for sid in (
        "JOEU-FM", "RNB", "LFR", "QRR", "TBS", "FMT",
        "ABC", "CCL", "802", "FMO", "MBS", "OBC", "KBS",
        "ALPHA-STATION", "E-RADIO", "CRK",
        "HBC", "TBC", "CBC", "RCC", "RKB", "KBC",
        "FMOTOKUNI", "FM845", "BARIBARI", "NIIHAMA", "FMGAIYA",
    ):
        if f'{RADIO_RAILWAY_BASE}/{sid}' not in radio_section:
            raise RuntimeError(f"required Railway radio station missing: {sid}")

    FREEWIFI.write_text(updated, encoding="utf-8")
    print(
        f"FreeWiFi compact radio restored: {vercel_count} Vercel + "
        f"{render_count} Railway image+audio stations"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
