#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import re
import urllib.parse
from pathlib import Path
from urllib.parse import quote

FREEWIFI = Path("freewifi")
RADIO_AUDIO_BASE = "https://himitsu-six.vercel.app/api/radiko"
RADIO_RENDER_BASE = "https://ajiousama-radiko.onrender.com/radio-tv"
RADIO_BUILD = "20260907a"
LOGO_RAW_BASE = "https://raw.githubusercontent.com/ajiousama/himitsu/main"
EXPECTED_RADIO_COUNT = 16


def radio_url(sid: str) -> str:
    return f"{RADIO_RENDER_BASE}/{quote(sid, safe='')}?v={RADIO_BUILD}"


def source_logo_url(sid: str) -> str:
    return f"https://radiko.jp/v2/static/station/logo/{sid}/lrtrim/688x160.png"


def safe_slug(value: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip())
    return value.strip("._-") or "logo"


def contrast_logo_url(tvgid: str, sid: str) -> str:
    source = source_logo_url(sid)
    digest = hashlib.sha1(source.encode("utf-8")).hexdigest()[:8]
    relpath = f"logos/contrast/{safe_slug(tvgid)}_{digest}.png"
    return f"{LOGO_RAW_BASE}/{urllib.parse.quote(relpath, safe='/._-')}"


def radiko_entry(tvgid: str, sid: str, name: str, logo: str | None = None) -> str:
    if logo is None:
        # Use the local white-card asset generated by logo_contrast_apply.py.
        # This keeps black-background IPTV clients from swallowing dark or
        # transparent station artwork.
        logo = contrast_logo_url(tvgid, sid)
    return (
        f'#EXTINF:-1 tvg-id="{tvgid}" tvg-logo="{logo}" group-title="ラジオ",{name}\n'
        f'{radio_url(sid)}\n'
    )


def compact_block() -> str:
    parts: list[str] = ["## ラジオ\n\n"]

    stations = [
        ("radiko.JOEU-FM", "JOEU-FM", "FM愛媛（ラジオ）"),
        ("radiko.RNB", "RNB", "RNB南海放送（ラジオ）"),
        ("radiko.LFR", "LFR", "ニッポン放送（ラジオ）"),
        ("radiko.QRR", "QRR", "文化放送（ラジオ）"),
        ("radiko.TBS", "TBS", "TBSラジオ（ラジオ）"),
        ("radiko.FMT", "FMT", "TOKYO FM（ラジオ）"),
        ("radiko.ABC", "ABC", "ABCラジオ（ラジオ）"),
        ("radiko.CCL", "CCL", "FM COCOLO（ラジオ）"),
        ("radiko.802", "802", "FM802（ラジオ）"),
        ("radiko.FMO", "FMO", "FM大阪（ラジオ）"),
        ("radiko.MBS", "MBS", "MBSラジオ（ラジオ）"),
        ("radiko.OBC", "OBC", "OBCラジオ大阪（ラジオ）"),
        ("radiko.KBS", "KBS", "KBS京都ラジオ（ラジオ）"),
        ("radiko.ALPHA-STATION", "ALPHA-STATION", "α-STATION FM KYOTO（ラジオ）"),
        ("radiko.E-RADIO", "E-RADIO", "e-radio FM滋賀（ラジオ）"),
        ("radiko.CRK", "CRK", "ラジオ関西（ラジオ）"),
    ]
    parts.extend(radiko_entry(tvgid, sid, name) for tvgid, sid, name in stations)

    return "".join(parts).rstrip() + "\n\n"


def main() -> int:
    text = FREEWIFI.read_text(encoding="utf-8-sig", errors="replace")
    start = text.find("## ラジオ")
    end = text.find("## 愛媛CATV", start + 1)
    if start < 0 or end < 0 or end <= start:
        raise RuntimeError("could not locate radio section boundaries")

    updated = text[:start] + compact_block() + text[end:]

    if "## Rakuten-JP" not in updated:
        raise RuntimeError("Rakuten-JP section disappeared; refusing to write")

    radio_section = updated[start:updated.find("## 愛媛CATV", start)]
    render_count = radio_section.count(RADIO_RENDER_BASE + "/")
    if render_count != EXPECTED_RADIO_COUNT:
        raise RuntimeError(f"compact FreeWiFi image+audio radio count unexpected: {render_count}")
    if RADIO_AUDIO_BASE + "?station=" in radio_section:
        raise RuntimeError("audio-only route leaked into FreeWiFi radio section")
    if "NHKラジオ" in radio_section or "NHK-FM" in radio_section or "nhk_r1_" in radio_section or "nhk_fm_" in radio_section:
        raise RuntimeError("NHK radio leaked into FreeWiFi radio section")
    extinf_lines = [line for line in radio_section.splitlines() if line.startswith("#EXTINF:")]
    if len(extinf_lines) != EXPECTED_RADIO_COUNT or any('group-title="ラジオ"' not in line for line in extinf_lines):
        raise RuntimeError("FreeWiFi radio groups are not uniformly ラジオ")
    if "### 北海道" in radio_section:
        raise RuntimeError("nationwide catalog leaked into FreeWiFi radio section")
    if "raw.githubusercontent.com/ajiousama/himitsu/radio-ts-assets/" in radio_section:
        raise RuntimeError("TS visual master leaked into compact FreeWiFi radio section")
    if radio_section.count("/logos/contrast/radiko.") != EXPECTED_RADIO_COUNT:
        raise RuntimeError("contrast-safe compact radio logos are not complete")

    required_sids = ("LFR", "QRR", "TBS", "FMT")
    for sid in required_sids:
        if f'{RADIO_RENDER_BASE}/{sid}' not in radio_section:
            raise RuntimeError(f"required Tokyo radio station missing: {sid}")

    FREEWIFI.write_text(updated, encoding="utf-8")
    print(f"FreeWiFi compact radio restored: {render_count} image+audio stations with contrast-safe logos")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
