// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: cyan; icon-glyph: magic;

// 公営これ一発 v17
// BOAT 24場取得 + 手動強制更新
// ・YouTube 手動更新
// ・オート／競輪／地方競馬 EPG 強制取得
// ・ラジオ + ラジオEPG 強制取得
// BOATRACEはearphone + ajiousamaへ同時反映し、ajiousama側はdirect Streaks seedのみ使用

const OWNER="earphone1981", REPO="public-sports-iptv", BRANCH="main";
const TOKEN_KEY="public_sports_github_pat_v4";
const HIM_OWNER="ajiousama", HIM_REPO="himitsu", HIM_BRANCH="main";
const HIM_TOKEN_KEY="himitsu_github_pat_v1";
const HIM_ALL_WORKFLOW="update_freewifi_epg.yml";
const HIM_RADIO_WORKFLOW="force_freewifi_radio_vercel.yml";
const HIM_BOAT_WORKFLOW="update_boat_today.yml";
const RAW_BASE=`https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}`;
const API_REPO=`/repos/${OWNER}/${REPO}`;
const HIM_API_REPO=`/repos/${HIM_OWNER}/${HIM_REPO}`;
const EPG_URL=`${RAW_BASE}/epg.xml`;
const UA="Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1";

const BOAT=[["01kiryu","boat.kiryu","BOATRACE桐生","桐生","01_kiryu.png"],["02toda","boat.toda","BOATRACE戸田","戸田","02_toda.png"],["03edogawa","boat.edogawa","BOATRACE江戸川","江戸川","03_edogawa.png"],["04heiwajima","boat.heiwajima","BOATRACE平和島","平和島","04_heiwajima.png"],["05tamagawa","boat.tamagawa","BOATRACE多摩川","多摩川","05_tamagawa.png"],["06hamanako","boat.hamanako","BOATRACE浜名湖","浜名湖","06_hamanako.png"],["07gamagori","boat.gamagori","BOATRACE蒲郡","蒲郡","07_gamagori.png"],["08tokoname","boat.tokoname","BOATRACE常滑","常滑","08_tokoname.png"],["09tsu","boat.tsu","BOATRACE津","津","09_tsu.png"],["10mikuni","boat.mikuni","BOATRACE三国","三国","10_mikuni.png"],["11biwako","boat.biwako","BOATRACEびわこ","びわこ","11_biwako.png"],["12suminoe","boat.suminoe","BOATRACE住之江","住之江","12_suminoe.png"],["13amagasaki","boat.amagasaki","BOATRACE尼崎","尼崎","13_amagasaki.png"],["14naruto","boat.naruto","BOATRACE鳴門","鳴門","14_naruto.png"],["15marugame","boat.marugame","BOATRACE丸亀","丸亀","15_marugame.png"],["16kojima","boat.kojima","BOATRACE児島","児島","16_kojima.png"],["17miyajima","boat.miyajima","BOATRACE宮島","宮島","17_miyajima.png"],["18tokuyama","boat.tokuyama","BOATRACE徳山","徳山","18_tokuyama.png"],["19shimonoseki","boat.shimonoseki","BOATRACE下関","下関","19_shimonoseki.png"],["20wakamatsu","boat.wakamatsu","BOATRACE若松","若松","20_wakamatsu.png"],["21ashiya","boat.ashiya","BOATRACE芦屋","芦屋","21_ashiya.png"],["22fukuoka","boat.fukuoka","BOATRACE福岡","福岡","22_fukuoka.png"],["23karatsu","boat.karatsu","BOATRACE唐津","唐津","23_karatsu.png"],["24omura","boat.omura","BOATRACE大村","大村","24_omura.png"]];
const JRA=[["jra.gch","グリーンチャンネル","グリーンチャンネル（高画質）","gchmain.m3u8","gch.png"],["jra.gch","グリーンチャンネル","グリーンチャンネル（低画質）","gchmain_LQ.m3u8","gch.png"],["jra.east","JRA EAST","JRA EAST（高画質）","EAST_test.m3u8","east_web3.png"],["jra.east","JRA EAST","JRA EAST（低画質）","EAST_test_LQ.m3u8","east_web3.png"],["jra.west","JRA WEST","JRA WEST（高画質）","WEST_master .m3u8","west_web4.png"],["jra.west","JRA WEST","JRA WEST（低画質）","WEST_master_LQ.m3u8","west_web4.png"],["jra.hokkaido","JRA HOKKAIDO","JRA HOKKAIDO（高画質）","hokaido_master (1).m3u8","hokkaido_local.png"],["jra.hokkaido","JRA HOKKAIDO","JRA HOKKAIDO（低画質）","hokaido_master_LQ.m3u8","hokkaido_local.png"]];
function rawUrl(p){return RAW_BASE+"/"+p.split("/").map(encodeURIComponent).join("/");}
function japanDate(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());return p.find(x=>x.type==="year").value+p.find(x=>x.type==="month").value+p.find(x=>x.type==="day").value;}
async function getSavedToken(key,title){if(Keychain.contains(key))return Keychain.get(key);const a=new Alert();a.title=title;a.message="初回のみ入力。保存後は自動です。";a.addSecureTextField("github_pat_...");a.addAction("保存");a.addCancelAction("中止");if(await a.present()===-1)throw new Error(`${title} 入力中止`);const t=a.textFieldValue(0).trim();if(!t)throw new Error(`${title} が空です`);Keychain.set(key,t);return t;}
async function githubRequest(path,token,method="GET",body=null){const r=new Request(`https://api.github.com${path}`);r.method=method;r.headers={Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"Scriptable-Public-Sports-v17"};if(body!==null){r.headers["Content-Type"]="application/json";r.body=JSON.stringify(body);}const d=await r.load();const s=r.response?.statusCode??0,t=d.toRawString();if(s<200||s>=300)throw new Error(`GitHub API ${s}\n${t.slice(0,500)}`);try{return t?JSON.parse(t):{};}catch{return t;}}
function b64(t){return Data.fromString(t).toBase64String();}
async function uploadFileTo(apiRepo,branch,path,content,token,message){const ep=path.split("/").map(encodeURIComponent).join("/");let sha=null;try{const c=await githubRequest(`${apiRepo}/contents/${ep}?ref=${branch}`,token);sha=c.sha??null;if(c.content){const old=Data.fromBase64String(c.content.replace(/\n/g,"")).toRawString();if(old===content)return false;}}catch(e){if(!String(e).includes("GitHub API 404"))throw e;}const body={message,content:b64(content),branch};if(sha)body.sha=sha;await githubRequest(`${apiRepo}/contents/${ep}`,token,"PUT",body);return true;}
async function getRaw(path){const r=new Request(rawUrl(path));r.headers={"Cache-Control":"no-cache","User-Agent":UA};r.timeoutInterval=30;return await r.loadString();}
function readEntries(text){const l=String(text||"").replace(/\r/g,"").split("\n"),out=[];for(let i=0;i<l.length;i++){const e=l[i].trim();if(!e.startsWith("#EXTINF:"))continue;const opts=[];let u=null;for(let j=i+1;j<l.length;j++){const n=l[j].trim();if(!n)continue;if(n.startsWith("#EXTINF:"))break;if(n.startsWith("#")){opts.push(n);continue;}u=n;break;}if(u)out.push({extinf:e,options:opts,url:u});}return out;}
function tvgId(e){const m=String(e).match(/tvg-id="([^"]+)"/i);return m?m[1].trim():null;}
function previousBoat(text){const m=new Map();for(const x of readEntries(text)){const id=tvgId(x.extinf);if(id?.startsWith("boat.")&&!m.has(id))m.set(id,x.url);}return m;}
function findStreamUrl(d){if(!d)return null;if(Array.isArray(d)){for(const x of d){const f=findStreamUrl(x);if(f)return f;}return null;}if(typeof d==="object"){if(Array.isArray(d.sources))for(const s of d.sources){if(typeof s?.src==="string")return s.src;if(typeof s?.url==="string")return s.url;}for(const k of Object.keys(d)){const v=d[k];if(typeof v==="string"&&(v.includes(".m3u8")||v.includes("manifest")))return v;if(v&&typeof v==="object"){const f=findStreamUrl(v);if(f)return f;}}}return null;}
function isDirectStreaks(u){return typeof u==="string"&&u.startsWith("https://manifest.streaks.jp/")&&u.includes(".m3u8");}
async function makeBoat(existing){const date=japanDate(),prev=previousBoat(existing);let text="#EXTM3U\n\n",seedText="#EXTM3U\n\n",directSeedCount=0,fresh=0,kept=0,missing=[],freshNames=[],keptNames=[];for(const [apiId,id,display,venue,logoFile] of BOAT){const api=`https://playback.api.streaks.jp/v1/projects/cp-boatrace-prod/medias/ref:lm-br-${apiId}-tokyo-${date}?audio_only=false`;let stream=null;try{const r=new Request(api);r.headers={"User-Agent":UA,Origin:"https://front.player.boatrace-cdn.jp",Referer:"https://front.player.boatrace-cdn.jp/"};r.timeoutInterval=15;stream=findStreamUrl(await r.loadJSON());}catch(e){console.warn(`${venue} 当日URL取得失敗`,e);}let old=false;if(!stream&&prev.has(id)){stream=prev.get(id);old=true;}if(!stream){missing.push(venue);continue;}const logo=rawUrl(`public_sports_logos_github_43/boatrace/${logoFile}`);const entry=`#EXTINF:-1 tvg-id="${id}" tvg-name="${display}" tvg-logo="${logo}" group-title="ボートレース",${display}\n${stream}\n\n`;text+=entry;if(isDirectStreaks(stream)){seedText+=entry;directSeedCount++;}if(old){kept++;keptNames.push(venue);}else{fresh++;freshNames.push(venue);}}return{date,text,seedText,directSeedCount,fresh,kept,missing,total:fresh+kept,freshNames,keptNames};}
function append(out,label,text){const e=readEntries(text);if(!e.length)return;out.push(`## ${label}`);for(const x of e){out.push(x.extinf,...x.options,x.url,"");}}
async function makePublic(boat){const out=[`#EXTM3U url-tvg="${EPG_URL}"`,""];append(out,"競輪",await getRaw("keirin_master.m3u"));append(out,"地方競馬",await getRaw("keiba_master.m3u"));append(out,"オートレース",await getRaw("autorace_master.m3u"));append(out,"ボートレース",boat);out.push("## 中央競馬");for(const [id,name,display,file,logo] of JRA)out.push(`#EXTINF:-1 tvg-id="${id}" tvg-name="${name}" tvg-logo="${rawUrl(logo)}" group-title="中央競馬",${display}`,rawUrl(file),"");return out.join("\n").replace(/\n{3,}/g,"\n\n").trimEnd()+"\n";}
function saveICloud(name,text){const fm=FileManager.iCloud(),p=fm.joinPath(fm.documentsDirectory(),name);fm.writeString(p,text);}
async function dispatchPublicEPG(t){await githubRequest(`${API_REPO}/actions/workflows/update_epg_3days.yml/dispatches`,t,"POST",{ref:BRANCH});}
async function dispatchHimitsuWorkflow(t,w){await githubRequest(`${HIM_API_REPO}/actions/workflows/${w}/dispatches`,t,"POST",{ref:HIM_BRANCH});}
async function show(title,message){const a=new Alert();a.title=title;a.message=message;a.addAction("OK");await a.present();}
try{const token=await getSavedToken(TOKEN_KEY,"公営 GitHub Token");let existing="";try{existing=await getRaw("public_sports.m3u");}catch{}const boat=await makeBoat(existing);const publicM3U=await makePublic(boat.text);saveICloud("boatrace_today.m3u",boat.text);saveICloud("public_sports.m3u",publicM3U);await uploadFileTo(API_REPO,BRANCH,"boatrace_today.m3u",boat.text,token,`Update BOATRACE M3U v17 ${boat.date}`);const changed=await uploadFileTo(API_REPO,BRANCH,"public_sports.m3u",publicM3U,token,`Update public sports M3U v17 ${boat.date}`);let epg=false,manual=false,radio=false,freeToken=false,boatSeedOk=false,boatSeedChanged=false,boatState=false;try{await dispatchPublicEPG(token);epg=true;}catch(e){console.warn("公営EPG起動失敗",e);}try{const ht=await getSavedToken(HIM_TOKEN_KEY,"Free Wi-Fi GitHub Token");freeToken=true;try{boatSeedChanged=await uploadFileTo(HIM_API_REPO,HIM_BRANCH,"boat_stream_seed.m3u",boat.seedText,ht,`Update iPhone direct Streaks BOAT seed v17 ${boat.date}`);boatSeedOk=true;}catch(e){console.warn("BOAT seed更新失敗",e);}try{await dispatchHimitsuWorkflow(ht,HIM_BOAT_WORKFLOW);boatState=true;}catch(e){console.warn("BOAT状態更新起動失敗",e);}try{await dispatchHimitsuWorkflow(ht,HIM_ALL_WORKFLOW);manual=true;}catch(e){console.warn("YouTube/公営EPG手動更新起動失敗",e);}try{await dispatchHimitsuWorkflow(ht,HIM_RADIO_WORKFLOW);radio=true;}catch(e){console.warn("ラジオ/ラジオEPG強制取得起動失敗",e);}}catch(e){console.warn("Free Wi-Fi Token取得失敗",e);}let msg=`🚤 BOATRACE：24場すべて確認済み\n🟢 本日URL取得：${boat.fresh}場\n🟡 前回URL継続：${boat.kept}場\n⚫ 現在URLなし：${boat.missing.length}場\n📡 direct Streaks seed：${boat.directSeedCount}場\n💾 BOAT seed：${boatSeedOk?(boatSeedChanged?"更新":"変更なし"):"失敗"}\n🔄 BOAT状態更新：${boatState?"起動済み":"起動失敗"}\n\n`;if(boat.freshNames.length)msg+=`🟢 本日取得\n${boat.freshNames.join(" / ")}\n\n`;if(boat.keptNames.length)msg+=`🟡 前回URL継続\n${boat.keptNames.join(" / ")}\n\n`;if(boat.missing.length)msg+=`⚫ URLなし\n${boat.missing.join(" / ")}\n\n`;msg+=`📋 公営M3U：${changed?"更新":"変更なし"}\n📅 公営側EPG：${epg?"起動済み":"起動失敗"}\n🔑 Free Wi-Fi Token：${freeToken?"読込OK":"未設定/失敗"}\n\n🎬 YouTube 手動更新：${manual?"起動済み":"起動失敗"}\n🏁 オート EPG強制取得：${manual?"起動済み":"起動失敗"}\n🚴 競輪 EPG強制取得：${manual?"起動済み":"起動失敗"}\n🐎 地方競馬 EPG強制取得：${manual?"起動済み":"起動失敗"}\n📻 ラジオ 強制取得：${radio?"起動済み":"起動失敗"}\n📡 ラジオ EPG強制取得：${radio?"起動済み":"起動失敗"}\n\n※ BOATRACEは毎回24場すべて確認。\najiousama側へはdirect Streaks seedのみ送信し、直後にBOAT状態更新を起動します。`;await show("✅ 公営・FreeWiFi 一括更新 v17",msg);}catch(e){console.error(e);await show("❌ 公営・FreeWiFi 一括更新 v17 エラー",String(e));}Script.complete();